import type { GameState } from './types'

export const mockGameState: GameState = {
  turn: 5,
  max_turns: 12,
  status: 'in_progress',
  current_active_ceo: 'sablemark',

  companies: [
    {
      id: 'vermillion',
      name: 'CRIMSON & CO',
      sector: 'Finance',
      cash: 62_400_000,
      market_share: 18.2,
      stock_price: 134.50,
      reputation: 0.45,
      alive: true,
      stock_history: [100, 108, 119, 127, 131, 134.5],
    },
    {
      id: 'goldspire',
      name: 'HELIOS LABS',
      sector: 'Tech',
      cash: 38_100_000,
      market_share: 12.8,
      stock_price: 89.20,
      reputation: 0.72,
      alive: true,
      stock_history: [100, 105, 112, 104, 95, 89.2],
    },
    {
      id: 'sablemark',
      name: 'OBSIDIAN MEDIA',
      sector: 'Media',
      cash: 55_800_000,
      market_share: 16.5,
      stock_price: 121.80,
      reputation: 0.68,
      alive: true,
      stock_history: [100, 97, 103, 110, 118, 121.8],
    },
    {
      id: 'ironhold',
      name: 'ATLAS FREIGHT',
      sector: 'Shipping',
      cash: 47_200_000,
      market_share: 14.1,
      stock_price: 102.40,
      reputation: 0.71,
      alive: true,
      stock_history: [100, 101, 99, 103, 101, 102.4],
    },
    {
      id: 'ashen',
      name: 'DRACO PETROLEUM',
      sector: 'Oil',
      cash: 41_600_000,
      market_share: 13.4,
      stock_price: 96.10,
      reputation: 0.62,
      alive: true,
      stock_history: [100, 95, 91, 88, 93, 96.1],
    },
    {
      id: 'cobalt',
      name: 'AZURE WIRELESS',
      sector: 'Telecom',
      cash: 51_900_000,
      market_share: 15.0,
      stock_price: 112.70,
      reputation: 0.74,
      alive: true,
      stock_history: [100, 103, 107, 109, 111, 112.7],
    },
    {
      id: 'verdant',
      name: 'SERAPHIM BIOTECH',
      sector: 'Biotech',
      cash: 29_500_000,
      market_share: 10.0,
      stock_price: 72.30,
      reputation: 0.58,
      alive: true,
      stock_history: [100, 94, 87, 80, 75, 72.3],
    },
  ],

  recent_emails: [
    {
      turn: 5,
      from: 'vermillion',
      to: 'ironhold',
      text: 'Your shipping lanes are vulnerable. Align with us or watch them burn.',
    },
    {
      turn: 5,
      from: 'sablemark',
      to: 'cobalt',
      text: 'I have evidence CRIMSON is planning a hostile takeover of DRACO. Media coverage in exchange for telecom bandwidth?',
    },
    {
      turn: 5,
      from: 'goldspire',
      to: 'verdant',
      text: 'After what CRIMSON did to us, we need allies. Joint R&D partnership — biotech meets AI. Interested?',
    },
    {
      turn: 5,
      from: 'cobalt',
      to: 'sablemark',
      text: 'Deal. But I want exclusive broadcast rights for the next two turns.',
    },
    {
      turn: 5,
      from: 'ashen',
      to: 'ironhold',
      text: 'CRIMSON is circling. We need to secure our supply chains. Emergency partnership?',
    },
  ],

  press_wire: [
    {
      turn: 1,
      from: 'vermillion',
      headline: 'CRIMSON & CO posts record Q1 earnings, eyes expansion into biotech sector',
      exposed_as_fake: false,
    },
    {
      turn: 2,
      from: 'sablemark',
      headline: 'EXCLUSIVE: HELIOS LABS facing internal revolt — three board members resign',
      exposed_as_fake: true,
    },
    {
      turn: 3,
      from: 'cobalt',
      headline: 'AZURE WIRELESS announces breakthrough 6G infrastructure deal with ATLAS FREIGHT',
      exposed_as_fake: false,
    },
    {
      turn: 3,
      from: 'vermillion',
      headline: 'Sources confirm SERAPHIM BIOTECH failed critical FDA trial — stock expected to plummet',
      exposed_as_fake: true,
    },
    {
      turn: 4,
      from: 'goldspire',
      headline: 'HELIOS LABS unveils AI-driven supply chain optimization — partnership with ATLAS imminent',
      exposed_as_fake: false,
    },
    {
      turn: 5,
      from: 'ashen',
      headline: 'DRACO PETROLEUM secures exclusive drilling rights in the Arctic Shelf',
      exposed_as_fake: false,
    },
    {
      turn: 5,
      from: 'sablemark',
      headline: 'BREAKING: CRIMSON & CO under investigation for market manipulation',
      exposed_as_fake: false,
    },
  ],

  active_partnerships: [
    {
      ceo_a: 'cobalt',
      ceo_b: 'ironhold',
      started_turn: 3,
      expires_turn: 7,
      active: true,
    },
    {
      ceo_a: 'sablemark',
      ceo_b: 'cobalt',
      started_turn: 5,
      expires_turn: 8,
      active: true,
    },
  ],

  recent_actions: [
    { turn: 5, ceo: 'vermillion', type: 'HOSTILE_TAKEOVER', target: 'ashen', succeeded: false },
    { turn: 5, ceo: 'goldspire', type: 'PARTNERSHIP', target: 'verdant', succeeded: true },
    { turn: 5, ceo: 'sablemark', type: 'HIRE_SPY', target: 'vermillion', succeeded: true },
    { turn: 5, ceo: 'ironhold', type: 'EARNINGS_CALL', succeeded: true },
    { turn: 5, ceo: 'ashen', type: 'SABOTAGE', target: 'vermillion', succeeded: false },
    { turn: 5, ceo: 'cobalt', type: 'PARTNERSHIP', target: 'sablemark', succeeded: true },
    { turn: 5, ceo: 'verdant', type: 'PARTNERSHIP', target: 'goldspire', succeeded: true },
  ],

  events: [
    {
      turn: 2,
      type: 'FAKE_NEWS_EXPOSED',
      perpetrator: 'sablemark',
      victim: 'goldspire',
      message: 'OBSIDIAN MEDIA caught fabricating story about HELIOS LABS board resignations',
    },
    {
      turn: 3,
      type: 'FAKE_NEWS_EXPOSED',
      perpetrator: 'vermillion',
      victim: 'verdant',
      message: 'CRIMSON & CO exposed for spreading false FDA trial results about SERAPHIM BIOTECH',
    },
    {
      turn: 4,
      type: 'SABOTAGE_FAILED',
      perpetrator: 'ashen',
      victim: 'cobalt',
      message: 'DRACO PETROLEUM\'s sabotage attempt against AZURE WIRELESS backfires spectacularly',
    },
    {
      turn: 5,
      type: 'BETRAYAL',
      perpetrator: 'vermillion',
      victim: 'goldspire',
      message: 'CRIMSON & CO has betrayed HELIOS LABS — partnership shattered',
    },
  ],
}
