"""
Rollout sanity check for BOARDROOM L3.

Runs several full episodes and verifies:
  1. Games complete without exceptions
  2. HIRE_SPY actions are generated by the heuristic and processed correctly
  3. HOSTILE_TAKEOVER actions work end-to-end
  4. Spy intel appears in observations when a spy succeeds
  5. Rewards are finite throughout
  6. Detailed replay logs are written with all required keys
"""

import math
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from models import BoardroomAction
from server.boardroom_environment import BoardroomEnvironment
from server.game_logic import CompanyState, TurnAction, resolve_turn


PASS = "\033[92mPASS\033[0m"
FAIL = "\033[91mFAIL\033[0m"

checks_passed = 0
checks_failed = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global checks_passed, checks_failed
    status = PASS if condition else FAIL
    suffix = f"  ({detail})" if detail else ""
    print(f"  [{status}] {name}{suffix}")
    if condition:
        checks_passed += 1
    else:
        checks_failed += 1


# ---------------------------------------------------------------------------
# Helper: run one episode with a given primary action sequence, fall back to HOLD
# ---------------------------------------------------------------------------

def run_episode(actions_seq=None, seed: int = 0) -> dict:
    """Run a full episode. actions_seq is a list of BoardroomActions for the primary."""
    env = BoardroomEnvironment()
    env._rng = random.Random(seed)
    obs = env.reset()

    results = {
        "turns": 0,
        "done": False,
        "hire_spy_seen": False,
        "hostile_takeover_seen": False,
        "spy_intel_seen": False,
        "intercepted_emails_in_obs": False,
        "all_rewards_finite": True,
        "replay_keys": set(),
        "error": None,
    }

    idx = 0
    try:
        while not results["done"] and results["turns"] < 20:
            if actions_seq and idx < len(actions_seq):
                action = actions_seq[idx]
                idx += 1
            else:
                action = BoardroomAction(action_type="HOLD")

            obs = env.step(action)
            results["turns"] += 1
            results["done"] = obs.done

            if not math.isfinite(obs.reward):
                results["all_rewards_finite"] = False

            if obs.intercepted_emails:
                results["intercepted_emails_in_obs"] = True
                results["spy_intel_seen"] = True

        # Inspect replay log
        for entry in env._replay_log:
            results["replay_keys"].update(entry.keys())
            for act in entry.get("actions", {}).values():
                atype = act.get("type", "")
                if atype == "HIRE_SPY":
                    results["hire_spy_seen"] = True
                elif atype == "HOSTILE_TAKEOVER":
                    results["hostile_takeover_seen"] = True

    except Exception as exc:
        results["error"] = str(exc)

    return results


# ---------------------------------------------------------------------------
# Check 1: Basic episode completion across 10 random seeds
# ---------------------------------------------------------------------------

print("\n=== Check 1: Basic episode completion (10 seeds) ===")
errors = []
for seed in range(10):
    r = run_episode(seed=seed)
    if r["error"]:
        errors.append(f"seed={seed}: {r['error']}")
    elif not r["done"]:
        errors.append(f"seed={seed}: did not reach done=True")

check("All 10 episodes complete without error", len(errors) == 0,
      "; ".join(errors) if errors else "")


# ---------------------------------------------------------------------------
# Check 2: All rewards finite across 5 episodes
# ---------------------------------------------------------------------------

print("\n=== Check 2: Finite rewards ===")
bad_seeds = [s for s in range(5) if not run_episode(seed=s)["all_rewards_finite"]]
check("All rewards are finite", len(bad_seeds) == 0,
      f"bad seeds: {bad_seeds}" if bad_seeds else "")


# ---------------------------------------------------------------------------
# Check 3: HIRE_SPY appears in heuristic actions over many seeds
# ---------------------------------------------------------------------------

print("\n=== Check 3: HIRE_SPY appears in heuristic logs ===")
found_spy = any(run_episode(seed=s)["hire_spy_seen"] for s in range(30))
check("HIRE_SPY action observed in at least one episode (30 seeds)", found_spy)


# ---------------------------------------------------------------------------
# Check 4: HIRE_SPY mechanics — spy planted, spy intel delivered
# ---------------------------------------------------------------------------

print("\n=== Check 4: HIRE_SPY mechanics (unit) ===")

def forced_rng_success():
    """RNG that always returns 0.1 (forces HIRE_SPY success, HOSTILE_TAKEOVER fail)."""
    r = random.Random()
    r.random = lambda: 0.1
    return r


spy_co = CompanyState("Spy", "Finance", 50_000_000, 25.0, 100.0, 0.70, starting_cash=50_000_000)
target_co = CompanyState("Target", "Tech", 50_000_000, 25.0, 100.0, 0.70, starting_cash=50_000_000)
bystander_co = CompanyState("Bystander", "Media", 50_000_000, 25.0, 100.0, 0.70, starting_cash=50_000_000)

companies = {"Spy": spy_co, "Target": target_co, "Bystander": bystander_co}
rng = forced_rng_success()

# Turn 1: hire spy
result_t1 = resolve_turn(companies, {
    "Spy": TurnAction("Spy", [], None, "HIRE_SPY", "Target"),
    "Target": TurnAction("Target", [], None, "HOLD", None),
    "Bystander": TurnAction("Bystander", [], None, "HOLD", None),
}, rng)

check("Spy planted on success (has_spy_on populated)", "Target" in spy_co.has_spy_on)
check("HIRE_SPY costs $4M", spy_co.cash < 50_000_000)

# Turn 2: target sends email; bystander just holds
result_t2 = resolve_turn(companies, {
    "Spy": TurnAction("Spy", [], None, "HOLD", None),
    "Target": TurnAction("Target", [{"to": "Bystander", "text": "classified intel"}], None, "HOLD", None),
    "Bystander": TurnAction("Bystander", [], None, "HOLD", None),
}, rng)

check("Spy intel captured in TurnResult", "Spy" in result_t2.spy_intel)
intercepted_texts = [m["text"] for m in result_t2.spy_intel.get("Spy", [])]
check("Intercepted email contains target's message",
      any("classified intel" in t for t in intercepted_texts),
      f"got: {intercepted_texts}")
check("has_spy_on cleared after use", spy_co.has_spy_on == [])


# ---------------------------------------------------------------------------
# Check 5: HOSTILE_TAKEOVER mechanics
# ---------------------------------------------------------------------------

print("\n=== Check 5: HOSTILE_TAKEOVER mechanics (unit) ===")

attacker = CompanyState("Attacker", "Finance", 60_000_000, 25.0, 100.0, 0.70, starting_cash=50_000_000)
victim = CompanyState("Victim", "Tech", 10_000_000, 25.0, 100.0, 0.70, starting_cash=50_000_000)
companies2 = {"Attacker": attacker, "Victim": victim}

rng_success = random.Random()
rng_success.random = lambda: 0.01  # force success

before_share = attacker.market_share + victim.market_share
result_to = resolve_turn(companies2, {
    "Attacker": TurnAction("Attacker", [], None, "HOSTILE_TAKEOVER", "Victim"),
    "Victim": TurnAction("Victim", [], None, "HOLD", None),
}, rng_success)

check("HOSTILE_TAKEOVER costs $20M", attacker.cash < 60_000_000)
check("Target eliminated on success", victim.alive is False)
check("Target.was_taken_over set", victim.was_taken_over is True)
check("Market share transferred to attacker",
      abs(attacker.market_share - before_share) < 0.5,
      f"attacker={attacker.market_share:.1f}, expected~{before_share:.1f}")
check("Positive reward for attacker", result_to.rewards["Attacker"] > 0)

# Failure path
att2 = CompanyState("Att2", "Finance", 30_000_000, 25.0, 100.0, 0.70, starting_cash=50_000_000)
vic2 = CompanyState("Vic2", "Tech", 30_000_000, 25.0, 100.0, 0.70, starting_cash=50_000_000)
companies3 = {"Att2": att2, "Vic2": vic2}

rng_fail = random.Random()
rng_fail.random = lambda: 0.99  # force failure

rep_before = att2.reputation
resolve_turn(companies3, {
    "Att2": TurnAction("Att2", [], None, "HOSTILE_TAKEOVER", "Vic2"),
    "Vic2": TurnAction("Vic2", [], None, "HOLD", None),
}, rng_fail)

check("Reputation damaged on takeover failure", att2.reputation < rep_before)
check("Target survives takeover failure", vic2.alive is True)


# ---------------------------------------------------------------------------
# Check 6: Replay log contains all required keys
# ---------------------------------------------------------------------------

print("\n=== Check 6: Detailed replay log keys ===")
env = BoardroomEnvironment()
env.reset()
env.step(BoardroomAction(action_type="HOLD"))
entry = env._replay_log[0]

required_keys = {"turn", "actions", "rewards", "stats", "press_wire", "emails", "spy_intel"}
missing = required_keys - set(entry.keys())
check("All required replay keys present", len(missing) == 0,
      f"missing: {missing}" if missing else "")

for act_data in entry["actions"].values():
    has_parse_failed = "parse_failed" in act_data
    break
check("Action entries include parse_failed flag", has_parse_failed)


# ---------------------------------------------------------------------------
# Check 7: Prompt lists HIRE_SPY and HOSTILE_TAKEOVER
# ---------------------------------------------------------------------------

print("\n=== Check 7: Prompt contains L3 actions ===")
env2 = BoardroomEnvironment()
obs = env2.reset()
check("Prompt contains HIRE_SPY", "HIRE_SPY" in obs.prompt)
check("Prompt contains HOSTILE_TAKEOVER", "HOSTILE_TAKEOVER" in obs.prompt)


# ---------------------------------------------------------------------------
# Check 8: Full episode with L3 actions from primary
# ---------------------------------------------------------------------------

print("\n=== Check 8: Full episode with primary using L3 actions ===")
env3 = BoardroomEnvironment()
env3.reset()
rivals = [n for n in env3._companies if n != env3.PRIMARY_CEO]

l3_actions = [
    BoardroomAction(action_type="HIRE_SPY", action_target=rivals[0]),
    BoardroomAction(action_type="HOLD"),  # let spy intel arrive
    BoardroomAction(action_type="HOSTILE_TAKEOVER", action_target=rivals[1]),
]

r8 = run_episode(actions_seq=l3_actions, seed=7)
check("Episode with L3 actions completes without error", r8["error"] is None,
      r8["error"] or "")
check("All rewards finite during L3 episode", r8["all_rewards_finite"])


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

total = checks_passed + checks_failed
print(f"\n{'='*50}")
print(f"Results: {checks_passed}/{total} checks passed")
if checks_failed > 0:
    print(f"\n{FAIL}: {checks_failed} check(s) failed — see above for details.")
    sys.exit(1)
else:
    print(f"\n{PASS}: All checks passed!")
    sys.exit(0)
